title: Yahui Liu
position: Ph.D. Student
affiliation: Soochow University
email: yahuiliu.nlp@foxmail.com

plugins:
  - jekyll-spaceship
  - jekyll-last-modified-at
  # - jekyll-analytics

keywords: minimal academic
description:
  Zhang Jianxin, Ph.D. Candidate (Extended Year 6), School of Computer Science and Technology, Soochow University
canonical: https://tianxiexiaozhu77.github.io/

semantic_scholar: https://www.semanticscholar.org/me/library/all
google_scholar: https://scholar.google.com.hk/citations?hl=zh-CN&user=5ru5DOEAAAAJ
cv_link: ./assets/files/CV_lyh_20250807.pdf
github_link: https://github.com/tianxiexiaozhu77
# arxiv_link: 
affiliation_link: https://www.suda.edu.cn

avatar: ./assets/img/IDphoto.png
# favicon: ./assets/img/favicon.svg
# favicon_svg: ./assets/img/favicon-3.min.svg
# favicon: ./assets/img/favicon.png
# favicon_dark: ./assets/img/favicon-dark.png

# jekyll_analytics:
#   GoogleAnalytics:
#     id: UA-284490532-1

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
